matrix:
  include:
    # api build
    - language: node_js
      node_js: 13
      os: linux
      dist: bionic
      before_script:
        - cd api
      script:
        - npm install && npm run test
      git:
        quiet: true

    # web build
    - language: node_js
      node_js: 13
      os: linux
      dist: bionic
      before_script:
        - cd web
      script:
        - npm install
      git:
        quiet: true
    # here will be another build for mobile
